# Introduction to Numpy

In [3]:
new_list=[5,2,4,3,7,8,9,0,1,6]
new_list

[5, 2, 4, 3, 7, 8, 9, 0, 1, 6]

In [1]:
#importing Numpy as np for easy access to call
import numpy as np

In [1]:
#creating a list for height and weight
height=[56,73,90,37] 
weight=[90,74,83,34]
bmmi=height/weight
bmmi
#the error bellow shows that we can not divide a list by another list, therefore we had to conver list to array to be able to do so 

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
#here we are trying to convert list to array usin numpy already imported as np
arr_height=np.array(height)
arr_weight=np.array(weight)
arr_weight

array([90, 74, 83, 34])

In [6]:
arr_weight

array([90, 74, 83, 34])

In [7]:
arr_height

array([56, 73, 90, 37])

In [8]:
#now we can now divid our lists after converting to array
bmi=arr_height/arr_weight

In [9]:
bmi

array([ 0.62222222,  0.98648649,  1.08433735,  1.08823529])

In [11]:
#to check the type of our variable declared
type(bmi)

numpy.ndarray

In [10]:
#hands on another list conversion to array
h=[2,5,6]
w=[4,5,7]

hw=h+w
hw

[2, 5, 6, 4, 5, 7]

In [13]:
arr_h=np.array(h)
arr_w=np.array(w)

hrw=arr_h+arr_w
hrw

array([ 6, 10, 13])

In [14]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globals',
 '_import

In [16]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [18]:
arr_h>2

array([False,  True,  True], dtype=bool)

In [21]:
hrw>10

array([False, False,  True], dtype=bool)

In [22]:
np.random.rand(3,4)

array([[ 0.91292382,  0.49038921,  0.31240629,  0.20620685],
       [ 0.50612368,  0.49206596,  0.81863452,  0.03871134],
       [ 0.57797601,  0.65795608,  0.91200509,  0.35949009]])

In [27]:
np.random.choice(7)

5

In [28]:
np.random.seed(4) #to print the same random number for all

In [29]:
#to print random numbers between 0 and 1 to form a matrix of 3 by 4
np.random.rand(3,4)

array([[ 0.96702984,  0.54723225,  0.97268436,  0.71481599],
       [ 0.69772882,  0.2160895 ,  0.97627445,  0.00623026],
       [ 0.25298236,  0.43479153,  0.77938292,  0.19768507]])

In [31]:
okj=np.array([[2,4,3,5],[6,7,3,4]])
okj

array([[2, 4, 3, 5],
       [6, 7, 3, 4]])

In [36]:
okj[0][1]

4

In [37]:
okj[0][1:]

array([4, 3, 5])

In [38]:
okj[0,1:]

array([4, 3, 5])

In [39]:
okj[0,:3]

array([2, 4, 3])

In [40]:
np.mean(okj)

4.25

In [41]:
np.median(okj)

4.0

In [42]:
np.std(okj)

1.5612494995995996

In [53]:
hello=np.random.rand(4,2)
hello

array([[ 0.43614665,  0.94897731],
       [ 0.78630599,  0.8662893 ],
       [ 0.17316542,  0.07494859],
       [ 0.60074272,  0.16797218]])

In [45]:
np.dot(hello,okj) #to print the dot product of hello and okj

array([[  7.62639053,  10.33577768,   5.53918174,   8.24856889],
       [  3.91168815,   4.83670657,   2.28352856,   3.20854698],
       [  2.33739989,   2.74194337,   1.18667214,   1.59121562],
       [  5.82823792,   6.87321101,   3.00243908,   4.04741216]])

In [46]:
np.sum(okj)

34

In [47]:
np.sum(hello)

4.0039405040690124

In [48]:
np.sqrt(5)

2.2360679774997898

In [50]:
np.square(5)

25

In [51]:
np.cos(90)

-0.44807361612917013

In [52]:
np.sin(90)

0.89399666360055785

In [54]:
k= np.sin(90)
np.round(k)

1.0

In [55]:
np.count_nonzero(hello)

8

In [56]:
np.max(hello)

0.94897730678156278

In [57]:
np.corrcoef(hello)

array([[ 1.,  1., -1., -1.],
       [ 1.,  1., -1., -1.],
       [-1., -1.,  1.,  1.],
       [-1., -1.,  1.,  1.]])

In [58]:
np.corrcoef(okj)

array([[ 1.        , -0.14142136],
       [-0.14142136,  1.        ]])

In [59]:
np.round(hello)

array([[ 0.,  1.],
       [ 1.,  1.],
       [ 0.,  0.],
       [ 1.,  0.]])

In [60]:
okj.shape

(2, 4)

In [61]:
np.matmul(hello,okj)

array([[ 6.56615713,  8.38742773,  4.15537186,  5.97664246],
       [ 6.77034776,  9.20924903,  4.95778585,  7.39668712],
       [ 0.79602237,  1.2173018 ,  0.74434203,  1.16562146],
       [ 2.20931855,  3.57877617,  2.30614472,  3.67560234]])

In [62]:
np.arctan(90)

1.5596856728972892